version: 2.1

jobs:
  build:
    docker:
      - image: afonsoaugusto/base-ci:latest
    steps:
      - run:
          name: env
          command: |
            env

workflows:
  workflow:
    jobs:
      - build:
          context: CI